load("//bazel:rust.bzl", "rust")

rust.library(
    name = "cas",
    srcs = [
        "src/hash.rs",
        "src/lib.rs",
        "src/storage.rs",
        "src/storage_test.rs",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@crates//:bitflags",
        "@crates//:bytes",
        "@crates//:fastcdc",
        "@crates//:futures",
        "@crates//:object_store",
        "@crates//:serde",
        "@crates//:serde_bytes",
        "@crates//:sha2",
        "@crates//:tokio",
        "@crates//:zstd",
    ],
)

rust.test(
    name = "cas_test",
    size = "small",
    crate = ":cas",
    data = ["//:.rustfmt.toml"],
    deps = [
        "//syx/testing",
        "@crates//:object_store",
        "@crates//:tempfile",
        "@crates//:tokio",
    ],
)

rust.test_suite(
    name = "cas_test_suite",
    size = "small",
    srcs = [
        "tests/digest_fidelity.rs",
        "tests/digest_is_deterministic.rs",
        "tests/digest_is_sensitive.rs",
    ],
    data = ["//:.rustfmt.toml"],
    shared_srcs = ["tests/common/mod.rs"],
    deps = [
        ":cas",
        "//syx/cas_testing",
        "@crates//:cbor2",
        "@crates//:serde",
        "@crates//:serde_bytes",
        "@crates//:tokio",
    ],
)
